apps/dashboard/urls.py
from django.urls import path

from apps.account.views import *

from .views.dashboard.views import DashboardView
from .views.contact.views import *
from .views.social_media.views import *
from .views.service.views import *
from .views.category.views import *
from .views.portfolio.views import *
from .views.client.views import *
from .views.testimonial.views import *
from .views.skill.views import *
from .views.interents.views import *
from .views.resume.views import *


urlpatterns = [
    path('', DashboardView.as_view(), name='index'),
    path('profile/', UserView.as_view(), name='profile'),
    #Urls Contact
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/add', ContactCreateView.as_view(), name='contact_create'),
    path('contact/edit/<int:pk>', ContactUpdateView.as_view(), name='contact_update'),
    path('contact/delete/<int:pk>', ContactDeleteView.as_view(), name='contact_delete'),
    
    #Urls Social Media
    path('social-media/',SocialMediaView.as_view(),name='social_media'),
    path('social-media/json', SocialMediaListView.as_view(), name='social_media_json'),
    path('social-media/add', SocialMediaCreateView.as_view(), name='social_media_create'),
    path('social-media/edit/<int:pk>', SocialMediaUpdateView.as_view(), name='social_media_edit'),
    path('social-media/delete/<int:pk>', SocialMediaDeleteView.as_view(), name='social_media_delete'),

    #Urls Service
    path('service/',ServiceView.as_view(), name='service'),
    path('service/json',ServiceListView.as_view(), name='service_json'),
    path('service/add', ServiceCreateView.as_view(), name='service_create'),
    path('service/edit/<int:pk>', ServiceUpdateView.as_view(), name='service_edit'),
    path('service/delete/<int:pk>', ServiceDeleteView.as_view(), name='service_delete'),

    #Urls Category
    path('category/',CategoryView.as_view(), name='category'),
    path('category/json',CategoryListView.as_view(), name='category_json'),
    path('category/add', CategoryCreateView.as_view(), name='category_create'),
    path('category/edit/<int:pk>', CategoryUpdateView.as_view(), name='category_edit'),
    path('category/delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),

    #Urls Portfolio
    path('portfolio/',PortfolioView.as_view(), name='portfolio'),
    path('portfolio/json',PortfolioListView.as_view(), name='portfolio_json'),
    path('portfolio/add', PortfolioCreateView.as_view(), name='portfolio_create'),
    path('portfolio/edit/<int:pk>', PortfolioUpdateView.as_view(), name='portfolio_edit'),
    path('portfolio/delete/<int:pk>', PortfolioDeleteView.as_view(), name='portfolio_delete'),

    #Urls Client
    path('client/',ClientView.as_view(), name='client'),
    path('client/json',ClientListView.as_view(), name='client_json'),
    path('client/add', ClientCreateView.as_view(), name='client_create'),
    path('client/edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),

    #Urls Testimonial
    path('testimonial/',TestimonialView.as_view(), name='testimonial'),
    path('testimonial/json',TestimonialListView.as_view(), name='testimonial_json'),
    path('testimonial/add', TestimonialCreateView.as_view(), name='testimonial_create'),
    path('testimonial/edit/<int:pk>', TestimonialUpdateView.as_view(), name='testimonial_edit'),
    path('testimonial/delete/<int:pk>', TestimonialDeleteView.as_view(), name='testimonial_delete'),

    #Urls Skill
    path('skill/',SkillView.as_view(), name='skill'),
    path('skill/json',SkillListView.as_view(), name='skill_json'),
    path('skill/add', SkillCreateView.as_view(), name='skill_create'),
    path('skill/edit/<int:pk>', SkillUpdateView.as_view(), name='skill_edit'),
    path('skill/delete/<int:pk>', SkillDeleteView.as_view(), name='skill_delete'),

    #Urls Interents
    path('interent/',InterentView.as_view(), name='interents'),
    path('interent/json',InterentListView.as_view(), name='interents_json'),
    path('interent/add', InterentCreateView.as_view(), name='interents_create'),
    path('interent/edit/<int:pk>', InterentUpdateView.as_view(), name='interents_edit'),
    path('interent/delete/<int:pk>', InterentDeleteView.as_view(), name='interents_delete'),



    path('resume/',ResumeView.as_view(), name='resume'),
    path('resume/json',ResumeListView.as_view(), name='resume_json'),
    path('resume/add', ResumeCreateView.as_view(), name='resume_create'),
    path('resume/edit/<int:pk>', ResumeUpdateView.as_view(), name='resume_edit'),
    path('resume/delete/<int:pk>', ResumeDeleteView.as_view(), name='resume_delete'),
    path('resume/detail/add',ResumeDetailCreateView.as_view(),name='resume_detail_create'),
    path('resume/detail/delete/<int:pk>',ResumeDetailDeleteView.as_view(),name='resume_detail_delete'),
    path('resume/detail/<int:pk>',ResumeDetailView.as_view(),name='resume_detail'),
    
    path('resume/item/add',ResumeDetailItemCreateView.as_view(),name='resume_detail_item_add'),
    path('resume/item/json/<int:pk>',ResumeDetailItemListView.as_view(),name='resume_detail_item_json'),
    path('resume/item/edit/<int:pk>', ResumeDetailItemUpdateView.as_view(), name='resume_item_edit'),
    path('resume/item/delete/<int:pk>',ResumeDetailItemDeleteView.as_view(),name='resume_item_delete'),

]

portafolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.web.urls', 'web'), namespace='web')),
    path('login/',include(('apps.login.urls','lg'),namespace='lg')),
    path('dashboard/', include(('apps.dashboard.urls', 'dash'), namespace='dash')),

]

apps/dashboard/models.py
from django.db import models
from .modelos.model_contact import *
from .modelos.model_social_media import *
from .modelos.model_service import *
from .modelos.model_category import *
from .modelos.model_client import *
from .modelos.model_portfolio import *
from .modelos.model_testimonial import *
from .modelos.model_skills import *
from .modelos.model_interents import *
from .modelos.model_resume import *

apps/dashboard/views/category/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_category import *
from apps.dashboard.forms.form_category import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class CategoryView(LoginRequiredMixin,TemplateView):
    template_name = 'category/category.html'

class CategoryListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'category/category_json.html'
    model = Category
    context_object_name = 'category_info'
    success_url = 'dash:category'



class CategoryCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Category
    form_class = CategoryForm
    context_object_name = 'obj'
    template_name = 'category/category_form.html'
    success_url = 'dash:category'

        
class CategoryUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Category
    form_class = CategoryForm
    context_object_name = 'obj'
    template_name = 'category/category_form.html'
    success_url = 'dash:category'

    

class CategoryDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Category
    context_object_name = 'obj'
    template_name = 'category/category_delete.html'
    success_url = 'dash:category'

apps/dashboard/views/client/views.py
from django.http import JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_client import *
from apps.dashboard.forms.form_client import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class ClientView(LoginRequiredMixin,TemplateView):
    template_name = 'Client/client.html'

class ClientListView(JsonMixin,ListView):
    template_name = 'Client/client_json.html'
    model = Client
    context_object_name = 'client_info'


class ClientCreateView(CreateMixin,CreateView):
    model = Client
    form_class = ClientForm
    context_object_name = 'obj'
    template_name = 'Client/client_form.html'
    success_url = 'dash:cliente'

        
class ClientUpdateView(UpdateMixin,UpdateView):
    model = Client
    form_class = ClientForm
    context_object_name = 'obj'
    template_name = 'Client/client_form.html'
    success_url = 'dash:cliente'

class ClientDeleteView(DeleteMixin,DeleteView):
    model = Client
    context_object_name = 'obj'
    template_name = 'Client/client_delete.html'
    success_url = 'dash:cliente'

apps/dashboard/views/contact/views.py
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView,DeleteView

from apps.dashboard.modelos.model_contact import *
from apps.dashboard.forms.form_contact import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class ContactView(LoginRequiredMixin,ListView):
    template_name = 'Contact/contact.html'
    model = Contact
    context_object_name = 'contact_info'
    paginate_by = 3

    """
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = ContactForm(request.POST)
                if form.is_valid():
                    form.save()
                    data = {'status': 1, 'message': 'Se ha Guardado Exitosamente'}
                else:
                    data = {'status': 0, 'message': form.errors}
            elif action == "edit":
                obj = get_object_or_404(Contact, id_contact=request.POST['id_contact'])
                form = ContactForm(request.POST or None,instance = obj )
                if form.is_valid():
                    form.icon = request.POST['icon']
                    form.title = request.POST['title']
                    form.description = request.POST['description']
                    form.save()
                    data = {'status': 1, 'message': 'Se ha Editado Exitosamente'}
                else:
                    data = {'status': 0, 'message': form.errors}
            elif action == "delete":
                form = Contact.objects.get(pk=request.POST['id_contact'])
                form.delete()
                data = {'status': 1, 'message': 'Ha sido Eliminado correctamente'}
            elif action == 'contact_info':
                data = [i.toJSON() for i in Contact.objects.all()]
            elif action == 'load_data':
                filter_data = Contact.objects.filter(id_contact=request.POST['id_contact'])
                if len(filter_data) == 0:
                    data = {'status': 0, 'message': 'Esa tarjeta no existe'}
                else:
                    for i in filter_data:
                        data = i.toJSON()
                    data = {'status': 1, 'message': data}
            else:
                data['error'] = 'Informacion y/o datos no estan cargados correctamente'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)
    """


class ContactCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Contact
    form_class = ContactForm
    context_object_name = 'obj'
    template_name = 'Contact/contact_form.html'
    success_url = 'dash:contact'


class ContactUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Contact
    form_class = ContactForm
    context_object_name = 'obj'
    template_name = 'Contact/contact_form.html'
    success_url = 'dash:contact'

class ContactDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Contact
    context_object_name = 'obj'
    template_name = 'Contact/contact_delete.html'
    success_url = 'dash:contact'

apps/dashboard/views/dashboard/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin,TemplateView):
    template_name = 'Dashboard/index.html'

apps/dashboard/views/interents/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_interents import *
from apps.dashboard.forms.form_interents import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class InterentView(LoginRequiredMixin,TemplateView):
    template_name = 'Interents/interents.html'

class InterentListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'Interents/interents_json.html'
    model = Interent
    context_object_name = 'interents_info'
    success_url = 'dash:interents'



class InterentCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Interent
    form_class = InterentForm
    context_object_name = 'obj'
    template_name = 'Interents/interents_form.html'
    success_url = 'dash:interents'

        
class InterentUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Interent
    form_class = InterentForm
    context_object_name = 'obj'
    template_name = 'Interents/interents_form.html'
    success_url = 'dash:interents'

    

class InterentDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Interent
    context_object_name = 'obj'
    template_name = 'Interents/interents_delete.html'
    success_url = 'dash:interents'

apps/dashboard/views/portfolio/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_portfolio import *
from apps.dashboard.forms.form_portfolio import *


from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class PortfolioView(LoginRequiredMixin,TemplateView):
    template_name = 'Portfolio/portfolio.html'

class PortfolioListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'Portfolio/portfolio_json.html'
    model = Portfolio
    context_object_name = 'portfolio_info'
    success_url = 'dash:portfolio'

    

class PortfolioCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Portfolio
    form_class = PortfolioForm
    context_object_name = 'obj'
    template_name = 'Portfolio/portfolio_form.html'
    success_url = 'dash:portfolio'


class PortfolioUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Portfolio
    form_class = PortfolioForm
    context_object_name = 'obj'
    template_name = 'Portfolio/portfolio_form.html'
    success_url = 'dash:portfolio'

class PortfolioDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Portfolio
    context_object_name = 'obj'
    template_name = 'Portfolio/portfolio_delete.html'
    success_url = 'dash:portfolio'

apps/dashboard/views/service/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_service import *
from apps.dashboard.forms.form_service import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin


class ServiceView(LoginRequiredMixin,TemplateView):
    template_name = 'service/service.html'

class ServiceListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'service/service_json.html'
    model = Service
    context_object_name = 'service_info'
    success_url = 'dash:service'


class ServiceCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Service
    form_class = ServiceForm
    context_object_name = 'obj'
    template_name = 'service/service_form.html'
    success_url = 'dash:service'

class ServiceUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Service
    form_class = ServiceForm
    context_object_name = 'obj'
    template_name = 'service/service_form.html'
    success_url = 'dash:service'

class ServiceDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Service
    context_object_name = 'obj'
    template_name = 'service/service_delete.html'
    success_url = 'dash:service'

apps/dashboard/views/skill/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_skills import *
from apps.dashboard.forms.form_skill import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class SkillView(LoginRequiredMixin,TemplateView):
    template_name = 'Skill/skill.html'

class SkillListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'Skill/skill_json.html'
    model = Skill
    context_object_name = 'skill_info'
    success_url = 'dash:skill'


class SkillCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Skill
    form_class = SkillForm
    context_object_name = 'obj'
    template_name = 'Skill/skill_form.html'
    success_url = 'dash:skill'

        
class SkillUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Skill
    form_class = SkillForm
    context_object_name = 'obj'
    template_name = 'Skill/skill_form.html'
    success_url = 'dash:skill'


class SkillDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Skill
    context_object_name = 'obj'
    template_name = 'Skill/skill_delete.html'
    success_url = 'dash:skill'

apps/dashboard/templates/Skill/skill.html
{% extends 'dashboard/base.html' %}
{% load static%}
{% block title_page %}Dashboard &mdash; Habilidades {% endblock %}
{% block title %}Habilidades{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <button type="button" onclick="abrir_modal('#popup','{% url 'dash:skill_create' %}');"
                        class="btn btn-primary mb-3 btn-lg mb-3"
                >Agregar <i class="fa fa-plus"></i>
                </button>
                <div class="col-12">
                    <table id="tableSkill" class="table table-striped first display responsive datatablem text-center" cellspacing="0"  style="width:100%">
                        <thead class="text-uppercase">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">HABILIDAD</th>
                                <th scope="col">PORCENTAJE</th>
                                <th scope="col">OPCIONES</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block extra_js%}
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
<script src="{% static 'dashboard/assets/ajax/functions_skill.js' %}"></script>
<script text="text/javascript">
var url_skill = '{% url 'dash:skill' %}';
var table_skill = $('#tableSkill').DataTable({
        "aProcessing":true,
        "responsive":true,
        "destroy": false,
        "searching": false,
        "aServerSide":true,
        "info": false,
        "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
        },
        "ajax":{
            "url" :url_skill+"json",
            "dataSrc":""
        },
        "columns":[
            {"data":"id_skill"},
            {"data":"name_skill"},
            {"data":"percentage"},
            {"data":"opciones"}
        ],
        "columnDefs":[
            {
                targets:[2],
                orderable:false,
                render:function(data,type,row){
                    let base_opcion = '<div class="progress" data-height="4" data-toggle="tooltip" title="" data-original-title="'+row.percentage+'%" style="height: 10px;">'+
                    '<div class="progress-bar bg-success" data-width="'+row.percentage+'" style="width: '+row.percentage+'px;"></div></div>';
                    return base_opcion;
                }

            },
            {
                targets:[3],
                orderable:false,
                render:function(data,type,row){
                    let url_edit = url_skill+"edit/"+row.id_skill
                    let url_delete = url_skill+"delete/"+row.id_skill
                    let base_opcion = '<div class="d-flex justify-content-center">'+
                    '<button type="button" onclick=abrir_modal("#popup","'+url_edit+'"); class="close text-primary"><i class="fa fa-edit"></i></button>'+
                    '<button type="button" onclick=abrir_modal("#popup","'+url_delete+'"); class="close text-danger"><i class="fa fa-trash"></i></button>';
                    return base_opcion;
                }

            }
        ], 
        "order":[[0,"desc"]]
    });
</script>
{% endblock %}

apps/dashboard/templates/Skill/skill_delete.html
{% extends 'dashboard/base_delete.html'%}
{% load widget_tweaks %}
{%  load static %}
{% block model_form %}
<form id="fntSkillDelete" method="POST" role="form"  action="{% url 'dash:skill_delete' obj.pk %}">
{% csrf_token %}
{% endblock%}
{% block model_title %}Eliminar Habilidad{% endblock%}
{% block model_content %}
<p>
    Desea Eliminar la habilidad <strong> {{ obj.name_skill}} </strong>
</p>                
{% endblock %}
{% block button_modal %}
<button type="submit" class="btn btn-danger">Si,Eliminar <i class="fas fa-trash"></i>
</button>   
{% endblock %}
{% block  js_functions %}
<script src="{% static 'dashboard/assets/ajax/functions_skill.js' %}"></script>
{% endblock %}    

apps/dashboard/templates/Skill/skill_form.html
{% extends 'dashboard/base_form.html' %}
{% load widget_tweaks %}
{%  load static %}
{% block model_form%}
    <div class="modal-content">
    {% if obj %}
    <form class="needs-validation" id="fntSkillUpdate"
    method="post" role="form" action="{% url 'dash:skill_edit' obj.pk%}" novalidate="">
    {% else %}
    <form class="needs-validation" id="fntSkillCreate" 
    method="post" role="form" action="{% url 'dash:skill_create'%}" novalidate="">
    {% endif %}
    {% csrf_token %}
{% endblock%}

{% block  model_title %}
    {% if obj %}Editar | Habilidad <i class="fa fa-edit"></i>
    {% else %} Crear | Habilidad <i class="fa fa-plus"></i>{% endif%}</span></h5>
{% endblock%}

{% block model_content %}
<div class="form-group">
    <div class="input-group">
        <div class="input-group-append">
            <span class="input-group-text">
                <i class="fa fa-text-height" aria-hidden="true"></i>
            </span>
        </div>
        {%if obj %}
        {{form.name_skill|attr:'placeholder:nombre'|attr:'class:form-control is-valid'}}
        {%else %}
        {{form.name_skill|attr:'placeholder:nombre'}}
        {% endif %}
        <div class="invalid-feedback">
            no puedes dejar el campo vacio
        </div>
    </div>
</div>
<div class="form-group">
    <div class="input-group">
        <div class="input-group-append">
            <span class="input-group-text">
                <i class="fa fa-percent" aria-hidden="true"></i>
            </span>
        </div>
        {%if obj %}
        {{form.percentage|attr:'placeholder:porcentaje'|attr:'class:form-control is-valid'}}
        {%else %}
        {{form.percentage|attr:'placeholder:porcentaje'}}
        {% endif %}
        <div class="invalid-feedback">
            no puedes dejar el campo vacio
        </div>
    </div>
</div>
{% endblock%}

{% block buttons_form %}
{% if obj %}Guardar <i class="fa fa-save"></i>
{% else%} Crear <i class="fa fa-plus"></i>{% endif%}</button>                    
{% endblock %}

{% block js_functions %}
<script src="{% static 'dashboard/assets/ajax/functions_skill.js' %}"></script>
{% endblock %}