apps/dashboard/urls.py
from django.urls import path

from apps.account.views import *

from .views.dashboard.views import DashboardView
from .views.contact.views import *
from .views.social_media.views import *
from .views.service.views import *
from .views.category.views import *
from .views.portfolio.views import *
from .views.client.views import *
from .views.testimonial.views import *
from .views.skill.views import *
from .views.interents.views import *
from .views.resume.views import *


urlpatterns = [
    path('', DashboardView.as_view(), name='index'),
    path('profile/', UserView.as_view(), name='profile'),
    #Urls Contact
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/add', ContactCreateView.as_view(), name='contact_create'),
    path('contact/edit/<int:pk>', ContactUpdateView.as_view(), name='contact_update'),
    path('contact/delete/<int:pk>', ContactDeleteView.as_view(), name='contact_delete'),
    
    #Urls Social Media
    path('social-media/',SocialMediaView.as_view(),name='social_media'),
    path('social-media/json', SocialMediaListView.as_view(), name='social_media_json'),
    path('social-media/add', SocialMediaCreateView.as_view(), name='social_media_create'),
    path('social-media/edit/<int:pk>', SocialMediaUpdateView.as_view(), name='social_media_edit'),
    path('social-media/delete/<int:pk>', SocialMediaDeleteView.as_view(), name='social_media_delete'),

    #Urls Service
    path('service/',ServiceView.as_view(), name='service'),
    path('service/json',ServiceListView.as_view(), name='service_json'),
    path('service/add', ServiceCreateView.as_view(), name='service_create'),
    path('service/edit/<int:pk>', ServiceUpdateView.as_view(), name='service_edit'),
    path('service/delete/<int:pk>', ServiceDeleteView.as_view(), name='service_delete'),

    #Urls Category
    path('category/',CategoryView.as_view(), name='category'),
    path('category/json',CategoryListView.as_view(), name='category_json'),
    path('category/add', CategoryCreateView.as_view(), name='category_create'),
    path('category/edit/<int:pk>', CategoryUpdateView.as_view(), name='category_edit'),
    path('category/delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),

    #Urls Portfolio
    path('portfolio/',PortfolioView.as_view(), name='portfolio'),
    path('portfolio/json',PortfolioListView.as_view(), name='portfolio_json'),
    path('portfolio/add', PortfolioCreateView.as_view(), name='portfolio_create'),
    path('portfolio/edit/<int:pk>', PortfolioUpdateView.as_view(), name='portfolio_edit'),
    path('portfolio/delete/<int:pk>', PortfolioDeleteView.as_view(), name='portfolio_delete'),

    #Urls Client
    path('client/',ClientView.as_view(), name='client'),
    path('client/json',ClientListView.as_view(), name='client_json'),
    path('client/add', ClientCreateView.as_view(), name='client_create'),
    path('client/edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),

    #Urls Testimonial
    path('testimonial/',TestimonialView.as_view(), name='testimonial'),
    path('testimonial/json',TestimonialListView.as_view(), name='testimonial_json'),
    path('testimonial/add', TestimonialCreateView.as_view(), name='testimonial_create'),
    path('testimonial/edit/<int:pk>', TestimonialUpdateView.as_view(), name='testimonial_edit'),
    path('testimonial/delete/<int:pk>', TestimonialDeleteView.as_view(), name='testimonial_delete'),

    #Urls Skill
    path('skill/',SkillView.as_view(), name='skill'),
    path('skill/json',SkillListView.as_view(), name='skill_json'),
    path('skill/add', SkillCreateView.as_view(), name='skill_create'),
    path('skill/edit/<int:pk>', SkillUpdateView.as_view(), name='skill_edit'),
    path('skill/delete/<int:pk>', SkillDeleteView.as_view(), name='skill_delete'),

    #Urls Interents
    path('interent/',InterentView.as_view(), name='interents'),
    path('interent/json',InterentListView.as_view(), name='interents_json'),
    path('interent/add', InterentCreateView.as_view(), name='interents_create'),
    path('interent/edit/<int:pk>', InterentUpdateView.as_view(), name='interents_edit'),
    path('interent/delete/<int:pk>', InterentDeleteView.as_view(), name='interents_delete'),



    path('resume/',ResumeView.as_view(), name='resume'),
    path('resume/json',ResumeListView.as_view(), name='resume_json'),
    path('resume/add', ResumeCreateView.as_view(), name='resume_create'),
    path('resume/edit/<int:pk>', ResumeUpdateView.as_view(), name='resume_edit'),
    path('resume/delete/<int:pk>', ResumeDeleteView.as_view(), name='resume_delete'),
    path('resume/detail/add',ResumeDetailCreateView.as_view(),name='resume_detail_create'),
    path('resume/detail/delete/<int:pk>',ResumeDetailDeleteView.as_view(),name='resume_detail_delete'),
    path('resume/detail/<int:pk>',ResumeDetailView.as_view(),name='resume_detail'),
    
    path('resume/item/add',ResumeDetailItemCreateView.as_view(),name='resume_detail_item_add'),
    path('resume/item/json/<int:pk>',ResumeDetailItemListView.as_view(),name='resume_detail_item_json'),
    path('resume/item/edit/<int:pk>', ResumeDetailItemUpdateView.as_view(), name='resume_item_edit'),
    path('resume/item/delete/<int:pk>',ResumeDetailItemDeleteView.as_view(),name='resume_item_delete'),

]

apps/login/urls.py
from django.urls import path
from apps.login.views import *

urlpatterns = [
    path('',LoginFormView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(), name='logout')

]

portafolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.web.urls', 'web'), namespace='web')),
    path('login/',include(('apps.login.urls','lg'),namespace='lg')),
    path('dashboard/', include(('apps.dashboard.urls', 'dash'), namespace='dash')),

]

apps/dashboard/views/category/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_category import *
from apps.dashboard.forms.form_category import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class CategoryView(LoginRequiredMixin,TemplateView):
    template_name = 'category/category.html'

class CategoryListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'category/category_json.html'
    model = Category
    context_object_name = 'category_info'
    success_url = 'dash:category'



class CategoryCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Category
    form_class = CategoryForm
    context_object_name = 'obj'
    template_name = 'category/category_form.html'
    success_url = 'dash:category'

        
class CategoryUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Category
    form_class = CategoryForm
    context_object_name = 'obj'
    template_name = 'category/category_form.html'
    success_url = 'dash:category'

    

class CategoryDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Category
    context_object_name = 'obj'
    template_name = 'category/category_delete.html'
    success_url = 'dash:category'

apps/dashboard/views/client/views.py
from django.http import JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_client import *
from apps.dashboard.forms.form_client import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class ClientView(LoginRequiredMixin,TemplateView):
    template_name = 'Client/client.html'

class ClientListView(JsonMixin,ListView):
    template_name = 'Client/client_json.html'
    model = Client
    context_object_name = 'client_info'


class ClientCreateView(CreateMixin,CreateView):
    model = Client
    form_class = ClientForm
    context_object_name = 'obj'
    template_name = 'Client/client_form.html'
    success_url = 'dash:cliente'

        
class ClientUpdateView(UpdateMixin,UpdateView):
    model = Client
    form_class = ClientForm
    context_object_name = 'obj'
    template_name = 'Client/client_form.html'
    success_url = 'dash:cliente'

class ClientDeleteView(DeleteMixin,DeleteView):
    model = Client
    context_object_name = 'obj'
    template_name = 'Client/client_delete.html'
    success_url = 'dash:cliente'

apps/dashboard/views/contact/views.py
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView,DeleteView

from apps.dashboard.modelos.model_contact import *
from apps.dashboard.forms.form_contact import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class ContactView(LoginRequiredMixin,ListView):
    template_name = 'Contact/contact.html'
    model = Contact
    context_object_name = 'contact_info'
    paginate_by = 3

    """
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = ContactForm(request.POST)
                if form.is_valid():
                    form.save()
                    data = {'status': 1, 'message': 'Se ha Guardado Exitosamente'}
                else:
                    data = {'status': 0, 'message': form.errors}
            elif action == "edit":
                obj = get_object_or_404(Contact, id_contact=request.POST['id_contact'])
                form = ContactForm(request.POST or None,instance = obj )
                if form.is_valid():
                    form.icon = request.POST['icon']
                    form.title = request.POST['title']
                    form.description = request.POST['description']
                    form.save()
                    data = {'status': 1, 'message': 'Se ha Editado Exitosamente'}
                else:
                    data = {'status': 0, 'message': form.errors}
            elif action == "delete":
                form = Contact.objects.get(pk=request.POST['id_contact'])
                form.delete()
                data = {'status': 1, 'message': 'Ha sido Eliminado correctamente'}
            elif action == 'contact_info':
                data = [i.toJSON() for i in Contact.objects.all()]
            elif action == 'load_data':
                filter_data = Contact.objects.filter(id_contact=request.POST['id_contact'])
                if len(filter_data) == 0:
                    data = {'status': 0, 'message': 'Esa tarjeta no existe'}
                else:
                    for i in filter_data:
                        data = i.toJSON()
                    data = {'status': 1, 'message': data}
            else:
                data['error'] = 'Informacion y/o datos no estan cargados correctamente'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)
    """


class ContactCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Contact
    form_class = ContactForm
    context_object_name = 'obj'
    template_name = 'Contact/contact_form.html'
    success_url = 'dash:contact'


class ContactUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Contact
    form_class = ContactForm
    context_object_name = 'obj'
    template_name = 'Contact/contact_form.html'
    success_url = 'dash:contact'

class ContactDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Contact
    context_object_name = 'obj'
    template_name = 'Contact/contact_delete.html'
    success_url = 'dash:contact'

apps/dashboard/views/dashboard/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin,TemplateView):
    template_name = 'Dashboard/index.html'

apps/dashboard/views/interents/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_interents import *
from apps.dashboard.forms.form_interents import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class InterentView(LoginRequiredMixin,TemplateView):
    template_name = 'Interents/interents.html'

class InterentListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'Interents/interents_json.html'
    model = Interent
    context_object_name = 'interents_info'
    success_url = 'dash:interents'



class InterentCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Interent
    form_class = InterentForm
    context_object_name = 'obj'
    template_name = 'Interents/interents_form.html'
    success_url = 'dash:interents'

        
class InterentUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Interent
    form_class = InterentForm
    context_object_name = 'obj'
    template_name = 'Interents/interents_form.html'
    success_url = 'dash:interents'

    

class InterentDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Interent
    context_object_name = 'obj'
    template_name = 'Interents/interents_delete.html'
    success_url = 'dash:interents'

apps/dashboard/views/portfolio/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_portfolio import *
from apps.dashboard.forms.form_portfolio import *


from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class PortfolioView(LoginRequiredMixin,TemplateView):
    template_name = 'Portfolio/portfolio.html'

class PortfolioListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'Portfolio/portfolio_json.html'
    model = Portfolio
    context_object_name = 'portfolio_info'
    success_url = 'dash:portfolio'

    

class PortfolioCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Portfolio
    form_class = PortfolioForm
    context_object_name = 'obj'
    template_name = 'Portfolio/portfolio_form.html'
    success_url = 'dash:portfolio'


class PortfolioUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Portfolio
    form_class = PortfolioForm
    context_object_name = 'obj'
    template_name = 'Portfolio/portfolio_form.html'
    success_url = 'dash:portfolio'

class PortfolioDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Portfolio
    context_object_name = 'obj'
    template_name = 'Portfolio/portfolio_delete.html'
    success_url = 'dash:portfolio'

apps/dashboard/views/service/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_service import *
from apps.dashboard.forms.form_service import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin


class ServiceView(LoginRequiredMixin,TemplateView):
    template_name = 'service/service.html'

class ServiceListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'service/service_json.html'
    model = Service
    context_object_name = 'service_info'
    success_url = 'dash:service'


class ServiceCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Service
    form_class = ServiceForm
    context_object_name = 'obj'
    template_name = 'service/service_form.html'
    success_url = 'dash:service'

class ServiceUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Service
    form_class = ServiceForm
    context_object_name = 'obj'
    template_name = 'service/service_form.html'
    success_url = 'dash:service'

class ServiceDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Service
    context_object_name = 'obj'
    template_name = 'service/service_delete.html'
    success_url = 'dash:service'

apps/dashboard/views/skill/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView,TemplateView
from apps.dashboard.modelos.model_skills import *
from apps.dashboard.forms.form_skill import *

from apps.dashboard.views.mixin.mixin import CreateMixin,UpdateMixin,DeleteMixin,JsonMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class SkillView(LoginRequiredMixin,TemplateView):
    template_name = 'Skill/skill.html'

class SkillListView(LoginRequiredMixin,JsonMixin,ListView):
    template_name = 'Skill/skill_json.html'
    model = Skill
    context_object_name = 'skill_info'
    success_url = 'dash:skill'


class SkillCreateView(LoginRequiredMixin,CreateMixin,CreateView):
    model = Skill
    form_class = SkillForm
    context_object_name = 'obj'
    template_name = 'Skill/skill_form.html'
    success_url = 'dash:skill'

        
class SkillUpdateView(LoginRequiredMixin,UpdateMixin,UpdateView):
    model = Skill
    form_class = SkillForm
    context_object_name = 'obj'
    template_name = 'Skill/skill_form.html'
    success_url = 'dash:skill'


class SkillDeleteView(LoginRequiredMixin,DeleteMixin,DeleteView):
    model = Skill
    context_object_name = 'obj'
    template_name = 'Skill/skill_delete.html'
    success_url = 'dash:skill'

templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>{% block title_page %} &mdash; {% endblock %}</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- CSS Libraries -->
    <link rel="shortcut icon" href="{% static 'web/assets/img/portafolio.svg'%}">
    <link href="{% static 'web/assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'web/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'web/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/assets/css/components.css' %}">
    {% block extra_css %}
    {% endblock %}

</head>
<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
          </ul>
        </form>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{{request.user.get_image}}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Hola,{{request.user.first_name}} {{request.user.last_name}}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
             
              <button type="button" 
                 onclick="abrir_modal('#popup','{% url 'dash:profile' %}');" class="dropdown-item"><i class="far fa-user"></i>   Perfil
              </button>
              
              <div class="dropdown-divider"></div>
                <a href="{% url 'lg:logout'%}" class="dropdown-item has-icon text-danger">
                  <i class="fas fa-sign-out-alt"></i> Cerrar Sesión
                </a>
            </div>
          </li>
        </ul>
      </nav>
      <div class="main-sidebar">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="index.html">Dashboard | Portafolio</a>
          </div>
          <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">DP</a>
          </div>
          <ul class="sidebar-menu">
              <li class="menu-header">MENU</li>
              <li class="nav-item dropdown {% if request.path == '/dashboard/' %}active{% endif %}">
                <a href="{% url 'dash:index'%}" class="nav-link"><i class="fas fa-fire"></i><span>Dashboard</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/contact/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:contact' %}"><i class="fas fa-address-book"></i> <span>Contacto</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/social-media/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:social_media' %}"><i class="fas fa-poll"></i><span>Redes Sociales</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/service/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:service' %}"><i class="fab fa-accusoft"></i><span>Mis Servicios</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/category/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:category' %}"><i class="fas fa-th-large"></i><span>Categorias</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/portfolio/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:portfolio' %}"><i class="fas fa-briefcase"></i><span>Portafolio</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/client/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:client' %}"><i class="fas fa-users"></i><span>Clientes</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/testimonial/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:testimonial' %}"><i class="far fa-comments"></i><span>Testimonios</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/interent/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:interents' %}"><i class="fas fa-tenge"></i><span>Intereses</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/skill/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:skill' %}"><i class="fas fa-cogs"></i>
                  <span>Habilidades</span></a>
              </li>
              <li class="{% if request.path == '/dashboard/resume/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'dash:resume' %}"><i class="fas fa-paste"></i>
                  <span>Resumen</span></a>
              </li>
            </ul>
        </aside>
      </div>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>{% block title %}{% endblock %}</h1>
          </div>
          <div class="section-body">
            {% block content %}
            {% endblock %}
          </div>
        </section>
      </div>
    </div>
  </div>

  <!-- General JS Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.16/dist/sweetalert2.all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@emretulek/jbvalidator"></script>
    <script src="{% static 'dashboard/assets/js/stisla.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Template JS File -->
    <script src="{% static 'dashboard/assets/js/scripts.js'%}"></script>

    <!-- Page Specific JS File -->

    <div class="modal fade"  role="dialog" id="popup">
    </div>
    {% block extra_js%}
    {% endblock%}
</body>
</html>

templates/dashboard/base_delete.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        {% block model_form %}
        {% endblock %}
            <div class="modal-header">
                <h5 class="modal-title">{% block model_title %}{% endblock%} </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times</span>
                </button>
            </div>
            <div class="modal-body">
                {% block model_content %}
                {% endblock %}
            </div>
            <div class="modal-footer">
                {% block button_modal %}
                {% endblock %}
            </div>
        </form>
    </div>
</div>
{% block  js_functions %}
{% endblock %}

templates/dashboard/base_form.html
{%  load static %}
<div class="modal-dialog modal-dialog-centered" role="document">
        {% block model_form %}
        {% endblock%}
            <div class="modal-header">
                <h5 class="modal-title"><span>
                    {% block  model_title%}
                    {% endblock%}
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times</span>
                    </button>
            </div>
            <div class="modal-body">
                {% block model_content %}
                {% endblock%}
                <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4 is-valid">
                    {% block buttons_form %}

                    {% endblock %}
                </button>
            </div>
            <div class="modal-footer">
            </div>
        </form>
    </div>
</div>
{% block js_functions %}
{% endblock %}